FORMAT: 1A
HOST: http://www.google.com

# Hanmer Accommodation Connector
The Hanmer Accommodation Connector is a service to keep a variety of accommodation booking engines in sync.

# Group Bookings
Bookings related resources

## Bookings Collection [/bookings]

### Create a Booking [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }
        
+ Request (application/xml)

        <title>Buy cheese and bread for breakfast.</title>

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }
        
+ Response 201 (application/xml)
        
        <id>3</id>
        <title>Buy cheese and bread for breakfast.</title>

## Booking [/bookings/{id}]
A single Booking object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Booking to perform action with.

### Retrieve a Booking [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }
            
### Update a Booking [PATCH]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }
        
+ Request (application/xml)

        <title>Buy cheese and bread for breakfast.</title>

+ Response 200


### Remove a Booking [DELETE]
+ Response 204

## Quotation [/bookings/{id}/quotation]
A single quotation with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Booking to perform action with.

### Retrieve Quotation [GET]
Get the Quotation associated with a specific booking
+ Response 200 (application/json)

## Ledger [/bookings/{id}/ledger]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Booking to perform action with.

### Retrieve Ledger [GET]
Get the Ledger associated with a specific booking
+ Response 200 (application/json)
